title: "Babylon.js 公式入門チュートリアル ざっくり和訳"
summary: "Web ブラウザ上で(も) 3D モデルを作ったり動かせたりする JavaScript の WebGL ライブラリ Babylon.js (バビロン ジェイ エス) の公式入門チュートリアルをざっくり和訳しました。(2022/4/03 時点で第 4 章まで。逐一 残りも公開していきます)"
topics: [BabylonJS, WebXR, WebGL, JavaScript]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 1-00
  - 1-01
  - 1-02
  - 1-03
  - 1-04
  - 2-00
  - 2-01
  - 2-02
  - 2-03
  - 2-04
  - 2-05
  - 2-06
  - 2-07
  - 2-08
  - 2-09
  - 2-10
  - 2-11
  - 3-00
  - 3-01
  - 3-02
  - 3-03
  - 3-04
  - 3-05
  - 3-06
  - 3-07
  - 4-00
  - 4-01
  - thankyou