title: "Babylon.js 公式入門チュートリアル ざっくり和訳"
summary: "Babylon.js の公式入門チュートリアルをざっくり和訳しました"
topics: [BabylonJS, WebXR]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 1-00
  - 1-01
  - 1-02
  - 1-03
  - 1-04
  - 2-00
  - 2-01
  - 2-02
  - 2-03
  - 2-04
  - 2-05
  - 2-06
